spring.application.name=emas

server.port=${PORT:8888}

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.ievnfyxqyizmrspsmydr
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=superSecretKeyForJwtTokenThatIsAtLeastThirtyTwoCharactersLong12345
jwt.expiration=86400000

spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheSizeMiB=0