spring.application.name=emas
server.port=8888

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.ievnfyxqyizmrspsmydr
spring.datasource.password=Sarthak@3035

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=superSecretKeyForJwtTokenThatIsAtLeastThirtyTwoCharactersLong12345
jwt.expiration=86400000
