package com.rscoe.emas.service.impl;

import com.rscoe.emas.entity.Attendance;
import com.rscoe.emas.entity.User;
import com.rscoe.emas.repository.AttendanceRepository;
import com.rscoe.emas.repository.UserRepository;
import com.rscoe.emas.service.AttendanceService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.rscoe.emas.dto.response.AttendanceResponse;
import com.rscoe.emas.enums.AttendanceStatus;

import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
public class AttendanceServiceImpl implements AttendanceService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private AttendanceRepository attendanceRepository;

    @Override
    public AttendanceResponse processScan(String token) {
        if (token == null || token.trim().isEmpty()) {
            throw new IllegalArgumentException("QR token cannot be null or empty");
        }

        // Clean the token prefix if it contains ATTENDANCE: generated by the backend
        String cleanToken = token;
        if (cleanToken.startsWith("ATTENDANCE:")) {
            cleanToken = cleanToken.substring("ATTENDANCE:".length());
        }

        // Find employee by their unique physical QR token using List to prevent NonUniqueResultException on bad data
        java.util.List<User> employees = userRepository.findByQrToken(cleanToken);
        
        if (employees.isEmpty()) {
            throw new RuntimeException("Invalid QR token");
        }
        if (employees.size() > 1) {
            throw new RuntimeException("Database error: Multiple users found for this QR token. Please clean up the database.");
        }
        User employee = employees.get(0);

        String email = employee.getEmail();

        LocalDate today = LocalDate.now();

        Optional<Attendance> attendanceOpt =
                attendanceRepository.findByEmployeeIdAndAttendanceDate(email, today);

        if(attendanceOpt.isEmpty()){

            Attendance attendance = new Attendance();

            attendance.setEmployeeId(email);
            attendance.setAttendanceDate(today);
            attendance.setCheckInTime(LocalDateTime.now());
            attendance.setScanToken(java.util.UUID.randomUUID().toString());
            attendance.setStatus(AttendanceStatus.CHECKED_IN);

            try {
                attendanceRepository.save(attendance);
            } catch (Exception ex) {
                ex.printStackTrace();
                throw new RuntimeException("Save attendance failed: " + ex.getMessage(), ex);
            }

            return toResponse(attendance, "Check-in recorded");
        }

        Attendance attendance = attendanceOpt.get();

        if(attendance.getCheckOutTime()==null){

            attendance.setCheckOutTime(LocalDateTime.now());
            attendance.setStatus(AttendanceStatus.CHECKED_OUT);

            double hours = Duration.between(attendance.getCheckInTime(), attendance.getCheckOutTime()).toMinutes() / 60.0;
            attendance.setTotalWorkingHours(Math.round(hours * 100.0) / 100.0);

            try {
                attendanceRepository.save(attendance);
            } catch (Exception ex) {
                ex.printStackTrace();
                throw new RuntimeException("Checkout attendance failed: " + ex.getMessage(), ex);
            }

            return toResponse(attendance, "Check-out recorded");
        }

        return toResponse(attendance, "Attendance already completed");
    }
    @Override
    public List<AttendanceResponse> getEmployeeAttendance(String employeeId){
        List<Attendance> records = attendanceRepository
                .findByEmployeeIdOrderByAttendanceDateDesc(employeeId);
        
        return records.stream().map(a -> toResponse(a, "History record")).toList();
    }

    private AttendanceResponse toResponse(Attendance attendance, String message) {
        AttendanceResponse res = new AttendanceResponse();
        res.setMessage(message);
        res.setStatus(attendance.getStatus() != null ? attendance.getStatus().name() : "");
        res.setAttendanceDate(attendance.getAttendanceDate() != null ? attendance.getAttendanceDate().toString() : "");
        res.setCheckInTime(attendance.getCheckInTime() != null ? attendance.getCheckInTime().toString() : "");
        res.setCheckOutTime(attendance.getCheckOutTime() != null ? attendance.getCheckOutTime().toString() : "");
        res.setTotalWorkingHours(attendance.getTotalWorkingHours());
        return res;
    }
}